<?php

namespace App\Tests\Unit;

use App\Service\Money\MoneyCompute;
use App\Service\Money\MoneyParser;
use PHPUnit\Framework\TestCase;

class MoneyComputeTest extends TestCase
{
    private MoneyCompute $moneyCompute;
    public function setUp(): void
    {
        $this->moneyCompute = new MoneyCompute(
            new MoneyParser('USD'),
            'USD'
        );
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAmount()
    {
        foreach($this->inputAmounts() as $amount)
        {
            $inputAmount = $this->moneyCompute->setAmount((string)$amount['input']);
           $this->assertEquals((string)$inputAmount->getDecimal(), (string)$amount['expectedOutput']);
        }
    }

    private function inputAmounts(): array
    {
        return [
            [
                'input' => '97.9',
                'expectedOutput' => '97.90'
            ],
            [
                'input' => '10000',
                'expectedOutput' => '10000.00'
            ],
            [
            'input' => '100.97',
            'expectedOutput' => '100.97'
            ],
        ];
    }
}